=== apergom/lmsgi-recetas-AntonioManuelPerezGomez/data/recetas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="saga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="categoria" type="xs:string"/>
                            <xs:element name="tiempo" type="xs:int"/>
                            <xs:element name="dificultad" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== apergom/lmsgi-recetas-AntonioManuelPerezGomez/data/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<saga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="recetas.xsd">

<receta>
    <nombre>Bloste con tomate </nombre>
    <categoria> Entrante </categoria>
    <tiempo> 33  </tiempo>
    <dificultad> Complicado </dificultad>

</receta>

<receta>
<nombre> Cariulenas con patatas </nombre>
<categoria> Principal </categoria>
<tiempo> 67  </tiempo>
<dificultad> Facil </dificultad>

</receta>

<receta>
<nombre> Yo, gurt </nombre>
<categoria> Postre</categoria>
<tiempo> 100 </tiempo>
<dificultad> Dificil </dificultad>

</receta>
</saga>
